version: '3.8'

services:
    # Identity Service (Production)
    identity-service:
        build:
            context: .
            target: production
        container_name: heapmind-identity-prod
        ports:
            - '3000:3000'
        environment:
            - NODE_ENV=production
            - MONGODB_URI=${MONGODB_URI}
            - JWT_SECRET=${JWT_SECRET}
            - PORT=${PORT:-3000}
        volumes:
            - ./logs:/app/logs
        networks:
            - heapmind-network
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    memory: 512M
                reservations:
                    memory: 256M

networks:
    heapmind-network:
        driver: bridge
